"""index.py -- the results index.  What exists, by file and line, so that
"if that were to work it would require ..." is a search and not a memory.

WHY.  Register rows V7, V9, V10: the model forgot T9's two halves for six
versions, summarised a run and missed the two facts in it that closed the
question, and said "nobody has asked" about a question the human had asked
three times in other words.  Every one of those is retrieval from memory.
This file makes retrieval mechanical: it walks the corpus and lists every
theorem / axiom / claim heading in the .md documents, every section verdict
and its docstring claim in the .py files, and every numbered ledger entry,
each with file:line.  The builder's requires-list cites lines from here.

USAGE.  python3 index.py <folder> [<folder> ...] > RESULTS-INDEX.md
        grep -i "retention" RESULTS-INDEX.md

Rows, not counts.
"""
import re, sys
from pathlib import Path

HEAD = re.compile(r"^\s*\|?\s*\*\*([A-Z]{1,3}\d+[′'″]*)\*?\*?\b\s*\|?\s*[—–-]?\s*([^\n]{0,160})")
TAG = re.compile(r"\[(AX|DEF|THM|FIN|OPEN|REF|AMD|AXIOM|THEOREM|PROVED[^\]]*|VERIFIED[^\]]*)\]")
VERD = re.compile(r'verdict\(\s*["\']([A-Za-z]+\d+[a-z]?)["\']\s*,\s*[^,]+,\s*["\']([^"\']{0,140})')
SECT = re.compile(r'^#\s*=+\s*([A-Z]+\d+[a-z]?)\s*$|^print\(\s*f?["\']\s*([A-Z]\d+)\.\s+([^"\']{0,120})')
SKIP = {".lake", "mathlib4-master", ".git", "build", "node_modules", "__pycache__",
        ".venv", "venv", "paper1_methodology", "hallucinated_papers", ".DS_Store"}
LEDG = re.compile(r"(?:[Cc]orrection\s+#|#)(\d{1,3})\b\.?\s*(.{0,120})")


def md_rows(path, lines):
    for i, line in enumerate(lines, 1):
        m = HEAD.match(line)
        if m:
            tags = " ".join(f"[{t}]" for t in TAG.findall(line))
            rest = m.group(2).replace("**", "").strip()
            yield f"{path}:{i} | {m.group(1).strip()} | {tags} | {rest[:140]}"


def py_rows(path, lines):
    text = "\n".join(lines)
    doc = re.match(r'\s*"""(.*?)"""', text, re.S)
    if doc:
        first = next((l.strip() for l in doc.group(1).splitlines() if l.strip()), "")
        yield f"{path}:1 | docstring | | {first[:160]}"
    for i, line in enumerate(lines, 1):
        m = VERD.search(line)
        if m:
            yield f"{path}:{i} | {m.group(1)} | verdict | {m.group(2)}"
            continue
        m = SECT.match(line)
        if m:
            name = m.group(1) or m.group(2)
            what = (m.group(3) or "").strip()
            yield f"{path}:{i} | {name} | section | {what}"


def log_rows(path, lines):
    """PROJECT-LOG.md: one row per entry -- the human's words are in the index too."""
    lid, what = None, None
    for i, line in enumerate(lines, 1):
        m = re.match(r"^## (L-\d{4}) · [^·]+ · (.+)$", line)
        if m:
            lid, disp, what = m.group(1), m.group(2).strip(), None
            start = i
            continue
        if lid and what is None and line.startswith("> "):
            what = line[2:].strip()
            yield f"{path}:{start} | {lid} | log ({disp}) | {what[:140]}"


def ledger_rows(path, lines):
    seen = set()
    for i, line in enumerate(lines, 1):
        for m in LEDG.finditer(line):
            n = int(m.group(1))
            if n in seen or n > 300:
                continue
            seen.add(n)
            yield f"{path}:{i} | #{n} | ledger | {m.group(2).strip()[:140]}"


def main(argv):
    roots = [Path(a) for a in argv] or [Path(".")]
    out = ["# RESULTS-INDEX -- generated by discipline/index.py; do not edit",
           "# file:line | item | tag/kind | claim (first 140 chars)", ""]
    for root in roots:
        files = [root] if root.is_file() else sorted(
            f for f in root.rglob("*") if f.suffix in (".md", ".py", ".out", ".lean")
            and not SKIP & set(f.parts))
        for f in files:
            try:
                lines = f.read_text(errors="replace").splitlines()
            except Exception:
                continue
            rel = str(f)
            if f.name == "PROJECT-LOG.md":
                out += list(log_rows(rel, lines))
            elif f.suffix == ".md":
                out += list(md_rows(rel, lines))
                out += list(ledger_rows(rel, lines))
            elif f.suffix == ".py":
                out += list(py_rows(rel, lines))
                out += list(ledger_rows(rel, lines))
            elif f.suffix == ".out":
                out += list(ledger_rows(rel, lines))
            elif f.suffix == ".lean":
                for i, line in enumerate(lines, 1):
                    m = re.match(r"\s*(theorem|lemma|axiom|def)\s+([A-Za-z_][A-Za-z0-9_.']*)", line)
                    if m:
                        out.append(f"{rel}:{i} | {m.group(2)} | lean {m.group(1)} | {line.strip()[:140]}")
    print("\n".join(out))
    return len(out) - 3


if __name__ == "__main__":
    n = main(sys.argv[1:])
    print(f"# {n} rows", file=sys.stderr)
